codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 10%

ignore:
  - "tests/**/*"
  - "setup.py"
  - "web/**/*"
  - "tools/**/*"
  - "docs/**/*"
  - "deployment/**/*" 