services:
  - type: web
    name: dirac-hashes-api
    env: docker
    repo: https://github.com/mk0dz/dirac-hashes
    dockerfilePath: ./Dockerfile
    dockerCommand: python run_api.py
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
    healthCheckPath: /api/hash/algorithms 